#!/bin/bash

package_name="$1"
package_path="$2"

if [ -z $1 -o -z $2 ]; then
    echo "Please give package name and package path" >&2
    echo "example : $(basename $0) xivo_sysconfd xivo-sysconfd"
    exit 1
fi

nosetests --cover-package=$package_name --with-xunit --with-coverage --cover-xml --cover-erase $package_path/$package_name
pep8 --repeat --ignore E320,E501 $package_path/$package_name > pep8.txt || true
PYTHONPATH=$package_path:$PYTHONPATH pylint --rcfile=/data/pylintrc $package_name > pylint.txt || true
